"""Catálogo editorial público de MotorFix Pro.

Las instrucciones son orientativas y evitan pares, capacidades o referencias
universales: esos datos siempre deben confirmarse para el vehículo concreto.
"""

from datetime import date

UPDATED = date.today().isoformat()


def guide(id, slug, title, category, description, difficulty, time, cost,
          tools, parts, warnings, steps):
    return {
        "id": id,
        "slug": slug,
        "title": title,
        "category": category,
        "description": description,
        "difficulty": difficulty,
        "time": time,
        "cost": cost,
        "tools": tools,
        "parts": parts,
        "warnings": warnings,
        "steps": steps,
        "updated": UPDATED,
    }


COMMON_LIFT_WARNING = "Nunca trabajes bajo un vehículo sostenido únicamente por el gato; usa apoyos homologados y terreno firme."
COMMON_SPEC_WARNING = "Confirma en el manual del vehículo la referencia, capacidad y procedimiento exactos antes de intervenir."


GUIDES = [
    guide(1, "cambio-aceite-filtro", "Cambio de aceite y filtro", "Mantenimiento",
          "Mantenimiento esencial para renovar el lubricante y proteger el motor.", "Fácil", "35–60 min", "35–90 €",
          ["Juego de llaves", "Recipiente para aceite", "Llave de filtro", "Embudo", "Guantes"],
          ["Aceite con especificación correcta", "Filtro de aceite", "Arandela del tapón si aplica"],
          [COMMON_SPEC_WARNING, COMMON_LIFT_WARNING, "Entrega el aceite usado en un punto autorizado."],
          ["Comprueba la especificación y cantidad de aceite.", "Estabiliza el vehículo y accede al tapón con seguridad.", "Vacía el aceite usado y sustituye el filtro.", "Monta el tapón y rellena gradualmente.", "Arranca brevemente, espera y verifica nivel y fugas."]),
    guide(2, "cambiar-pastillas-freno", "Cambiar pastillas de freno", "Frenos",
          "Revisión y sustitución orientativa de pastillas con comprobación del disco y la pinza.", "Media", "60–120 min", "45–180 €",
          ["Gato y borriquetas", "Llave de rueda", "Juego de vasos", "Útil retrae pistones"],
          ["Pastillas compatibles", "Sensor de desgaste si equipa"],
          [COMMON_LIFT_WARNING, "Los frenos son un sistema de seguridad: si no puedes verificar el montaje, acude a un profesional.", "Bombea el pedal antes de mover el coche."],
          ["Afloja la rueda, eleva y apoya el vehículo.", "Retira la rueda e inspecciona disco, latiguillos y pinza.", "Desmonta la pinza y retrae el pistón con el útil adecuado.", "Monta pastillas, chapas y sensores respetando su posición.", "Monta, aprieta según fabricante, bombea el pedal y prueba a baja velocidad."]),
    guide(3, "cambio-bateria-coche", "Cambiar la batería del coche", "Electricidad",
          "Sustitución de la batería de 12 V y comprobaciones básicas del sistema de carga.", "Fácil", "20–45 min", "80–220 €",
          ["Llaves o vasos", "Guantes", "Multímetro opcional"], ["Batería compatible"],
          ["Evita cortocircuitar los bornes.", "Algunos vehículos requieren registro o codificación de la batería.", "En híbridos y eléctricos utiliza solo los puntos de 12 V indicados por el fabricante."],
          ["Apaga el vehículo y confirma el procedimiento de memoria/codificación.", "Desconecta primero negativo y después positivo.", "Retira la sujeción y extrae la batería.", "Fija la nueva batería y conecta positivo y después negativo.", "Comprueba arranque, carga y realiza el registro si corresponde."]),
    guide(4, "cambio-filtro-aire", "Cambiar el filtro de aire", "Motor",
          "Sustitución del filtro de admisión para mantener un flujo de aire correcto.", "Fácil", "15–30 min", "15–45 €",
          ["Destornillador o Torx según modelo", "Aspirador opcional"], ["Filtro de aire compatible"],
          [COMMON_SPEC_WARNING, "Evita que entren objetos o suciedad en la admisión."],
          ["Localiza la caja del filtro.", "Abre sus grapas o tornillos.", "Retira el filtro observando la orientación.", "Limpia la caja sin contaminar la admisión.", "Asienta el filtro nuevo y cierra todas las fijaciones."]),
    guide(5, "cambiar-bujias", "Cambiar las bujías", "Motor",
          "Revisión y sustitución de bujías en motores de gasolina.", "Media", "45–120 min", "30–140 €",
          ["Vaso de bujía", "Carraca y alargador", "Llave dinamométrica"], ["Bujías con referencia correcta"],
          ["Trabaja con el motor frío.", "Una referencia o apriete incorrectos pueden dañar la culata."],
          ["Retira cubiertas y desconecta las bobinas.", "Limpia alrededor de los pozos.", "Extrae e inspecciona cada bujía.", "Instala las nuevas primero a mano.", "Aprieta al valor del fabricante y monta las bobinas."]),
    guide(6, "cambio-filtro-habitaculo", "Cambiar el filtro del habitáculo", "Mantenimiento",
          "Renovación del filtro de polen o carbón activo del sistema de ventilación.", "Fácil", "15–40 min", "12–40 €",
          ["Destornillador o Torx según modelo"], ["Filtro de habitáculo compatible"],
          ["Respeta la dirección de flujo indicada en el filtro."],
          ["Localiza el alojamiento.", "Retira tapas o fijaciones.", "Extrae el filtro observando la flecha de flujo.", "Limpia hojas y residuos.", "Monta el nuevo filtro y cierra el alojamiento."]),
    guide(7, "revisar-liquido-frenos", "Revisar el líquido de frenos", "Frenos",
          "Comprobación visual del nivel y del estado aparente del líquido de frenos.", "Fácil", "10–20 min", "0–20 €",
          ["Linterna", "Guantes"], ["Líquido con especificación correcta si procede"],
          ["El líquido puede dañar la pintura.", "Un nivel bajo puede indicar desgaste o fuga; no rellenes sin investigar la causa."],
          ["Localiza el depósito.", "Comprueba el nivel entre MIN y MAX.", "Observa color y contaminación visible.", "Busca indicios de fuga o desgaste.", "Consulta el intervalo de sustitución del fabricante."]),
    guide(8, "diagnosticar-fallo-iluminacion", "Diagnosticar un fallo de iluminación", "Electricidad",
          "Ruta inicial para diferenciar una lámpara, fusible, conexión o módulo defectuoso.", "Media", "20–90 min", "5–80 €",
          ["Multímetro", "Extractor de fusibles", "Herramientas básicas"], ["Lámpara o fusible según diagnóstico"],
          ["Sustituye fusibles solo por el mismo amperaje.", "Los faros xenón pueden trabajar con alta tensión."],
          ["Identifica si el fallo es unilateral o general.", "Comprueba la lámpara cuando sea accesible.", "Verifica el fusible correspondiente.", "Comprueba alimentación y masa solo si sabes medirlas.", "Si la alimentación es correcta, revisa conexión, módulo o cableado."]),
    guide(9, "pulir-restaurar-faros", "Pulir y restaurar faros", "Mantenimiento",
          "Recuperación de transparencia en faros opacos o amarillentos.", "Fácil", "45–90 min", "15–45 €",
          ["Cinta de carrocero", "Lijas al agua", "Pulimento", "Microfibra"], ["Kit de restauración", "Protector UV"],
          ["Protege la pintura alrededor del faro.", "Sin protección UV el acabado puede degradarse rápidamente."],
          ["Lava y seca el faro.", "Protege el contorno.", "Lija en húmedo de forma progresiva.", "Pulimenta hasta uniformar la superficie.", "Limpia y aplica protección UV."]),
    guide(10, "reparar-pinchazo-neumatico", "Reparar un pinchazo", "Neumáticos",
          "Actuación inicial ante un pinchazo localizado en la banda de rodadura.", "Fácil", "20–45 min", "8–25 €",
          ["Alicates", "Kit de reparación", "Compresor", "Manómetro"], ["Mecha o parche adecuado"],
          ["No repares daños en el flanco.", "Una mecha exterior debe considerarse temporal; solicita revisión interior profesional."],
          ["Localiza la fuga.", "Comprueba que el daño sea reparable.", "Retira el objeto si el sistema lo requiere.", "Aplica el método siguiendo su fabricante.", "Infla, verifica fugas y revisa la presión después."]),
    guide(11, "cambiar-rueda-coche", "Cambiar una rueda", "Neumáticos",
          "Sustitución segura de una rueda por la de repuesto.", "Muy fácil", "15–30 min", "0–20 €",
          ["Gato", "Llave de rueda", "Calzo"], ["Rueda de repuesto"],
          ["Trabaja sobre terreno firme y lejos del tráfico.", COMMON_LIFT_WARNING],
          ["Asegura y señaliza el vehículo.", "Afloja ligeramente los tornillos.", "Eleva desde el punto indicado.", "Sustituye la rueda y aprieta en cruz.", "Baja el vehículo y confirma el apriete final."]),
    guide(12, "cambiar-escobillas-limpiaparabrisas", "Cambiar las escobillas limpiaparabrisas", "Mantenimiento",
          "Sustitución de escobillas desgastadas para recuperar una limpieza uniforme.", "Muy fácil", "10–20 min", "10–35 €",
          ["Sin herramientas especiales"], ["Escobillas compatibles"], ["Evita que el brazo golpee el parabrisas."],
          ["Coloca los brazos en posición de servicio si corresponde.", "Levanta el brazo.", "Libera el anclaje.", "Instala la nueva escobilla hasta bloquearla.", "Baja el brazo con cuidado y comprueba el barrido."]),
    guide(13, "cambiar-bombilla-exterior", "Cambiar una bombilla exterior", "Electricidad",
          "Sustitución de una bombilla exterior averiada.", "Fácil", "15–40 min", "5–30 €",
          ["Guantes", "Destornillador si es necesario"], ["Bombilla compatible"],
          ["No toques el cristal de una halógena.", "Los sistemas LED o xenón pueden requerir intervención especializada."],
          ["Identifica la bombilla averiada.", "Apaga luces y contacto.", "Accede y libera el portalámparas.", "Monta la referencia correcta.", "Comprueba funcionamiento y orientación."]),
    guide(14, "arrancar-coche-con-pinzas", "Arrancar el coche con pinzas", "Batería",
          "Arranque auxiliar de un vehículo con la batería de 12 V descargada.", "Muy fácil", "10–20 min", "0–25 €",
          ["Cables de arranque o arrancador"], [],
          ["Respeta polaridad y orden de conexión.", "Consulta el manual de híbridos, eléctricos o coches con puntos remotos."],
          ["Apaga consumidores y ambos vehículos.", "Conecta los positivos.", "Conecta el negativo auxiliar y el punto de masa indicado.", "Arranca el auxiliar y después el descargado.", "Desconecta en orden inverso y revisa el sistema de carga."]),
    guide(15, "comprobar-presion-neumaticos", "Comprobar e inflar los neumáticos", "Neumáticos",
          "Ajuste de presión conforme a la etiqueta del vehículo.", "Muy fácil", "10–15 min", "0–5 €",
          ["Manómetro", "Compresor"], [],
          ["Mide preferiblemente en frío.", "Usa la presión del fabricante, no la cifra máxima del neumático."],
          ["Localiza la presión recomendada.", "Mide cada neumático.", "Añade o libera aire.", "Repite en todas las ruedas y la de repuesto si aplica.", "Monta tapones y reinicia el TPMS si corresponde."]),
    guide(16, "cambiar-fusible-coche", "Cambiar un fusible", "Electricidad",
          "Localización y sustitución de un fusible fundido.", "Muy fácil", "10–25 min", "1–5 €",
          ["Extractor de fusibles", "Linterna"], ["Fusible del mismo amperaje"],
          ["Nunca instales un fusible de mayor amperaje.", "Si vuelve a fundirse, detén las pruebas y diagnostica el circuito."],
          ["Consulta el esquema de fusibles.", "Apaga el circuito y el contacto.", "Retira y comprueba el fusible.", "Instala otro del mismo tipo y amperaje.", "Verifica el circuito y vigila si vuelve a fallar."]),
    guide(17, "cambiar-discos-freno", "Cambiar discos de freno", "Frenos",
          "Sustitución orientativa de discos junto con la revisión del conjunto de frenado.", "Difícil", "90–180 min", "100–400 €",
          ["Gato y borriquetas", "Llave dinamométrica", "Juego de vasos", "Útil de pistones"], ["Discos", "Pastillas", "Tornillería si es de un solo uso"],
          [COMMON_LIFT_WARNING, "Trabajo crítico de seguridad; requiere pares y procedimiento exactos.", "No contamines las superficies de fricción."],
          ["Eleva y apoya el vehículo.", "Retira rueda, pinza y soporte según manual.", "Retira el disco y limpia el buje.", "Monta disco, soporte, pastillas y pinza.", "Aprieta según fabricante, bombea el pedal y realiza el asentamiento indicado."]),
    guide(18, "diagnosticar-alternador", "Diagnosticar el alternador", "Electricidad",
          "Comprobaciones iniciales ante batería que no carga o testigo encendido.", "Media", "20–60 min", "0–40 €",
          ["Multímetro", "Linterna"], [],
          ["Evita cortocircuitos y partes móviles.", "No desconectes la batería con el motor en marcha."],
          ["Revisa batería, bornes y correa auxiliar.", "Comprueba el testigo y síntomas.", "Mide tensión en reposo.", "Mide carga con el motor en marcha y consumidores.", "Si los valores son anómalos, revisa cableado, regulación y alternador profesionalmente."]),
    guide(19, "cambiar-refrigerante", "Cambiar el refrigerante", "Refrigeración",
          "Renovación del líquido refrigerante y purgado orientativo del circuito.", "Media", "60–120 min", "25–90 €",
          ["Recipiente", "Embudo", "Guantes", "Herramientas básicas"], ["Refrigerante con especificación correcta"],
          ["Nunca abras el circuito en caliente.", "El refrigerante es tóxico; recógelo y entrégalo correctamente.", COMMON_SPEC_WARNING],
          ["Deja enfriar completamente el motor.", "Drena por el punto indicado.", "Cierra y rellena con la mezcla correcta.", "Purga siguiendo el procedimiento específico.", "Comprueba calefacción, temperatura, nivel y fugas tras enfriar."]),
    guide(20, "cambiar-termostato", "Cambiar el termostato", "Refrigeración",
          "Sustitución del termostato ante apertura incorrecta confirmada.", "Difícil", "90–240 min", "40–220 €",
          ["Herramientas básicas", "Recipiente", "Llave dinamométrica"], ["Termostato", "Junta", "Refrigerante"],
          ["Trabaja con el motor frío.", "Confirma el diagnóstico antes de sustituir piezas.", "Un purgado incorrecto puede causar sobrecalentamiento."],
          ["Confirma síntomas y ubicación.", "Drena el refrigerante necesario.", "Retira alojamiento y termostato.", "Limpia superficies y monta junta y termostato.", "Rellena, purga y comprueba temperatura y fugas."]),
    guide(21, "cambiar-filtro-combustible", "Cambiar el filtro de combustible", "Motor",
          "Sustitución del filtro manteniendo la limpieza y el cebado adecuados.", "Media", "30–90 min", "20–100 €",
          ["Herramientas básicas", "Recipiente", "Guantes"], ["Filtro de combustible compatible", "Juntas si aplica"],
          ["Trabaja lejos de llamas y chispas.", "Los sistemas de inyección pueden mantener alta presión.", COMMON_SPEC_WARNING],
          ["Identifica tipo, ubicación y procedimiento de despresurización.", "Protege y limpia la zona.", "Desconecta conductos y retira el filtro.", "Monta respetando sentido y juntas.", "Ceba si corresponde, arranca y comprueba fugas."]),
    guide(22, "cambiar-correa-auxiliar", "Cambiar la correa auxiliar", "Motor",
          "Sustitución de la correa que acciona alternador y otros accesorios.", "Media", "45–120 min", "30–160 €",
          ["Juego de llaves", "Útil del tensor si aplica"], ["Correa auxiliar", "Tensor o rodillos si están dañados"],
          ["Motor apagado y frío.", "Registra el recorrido exacto antes de retirar la correa."],
          ["Inspecciona recorrido, tensor y poleas.", "Descarga el tensor con el útil correcto.", "Retira la correa.", "Monta la nueva siguiendo el diagrama.", "Libera el tensor y comprueba alineación y funcionamiento."]),
    guide(23, "cambiar-kit-distribucion", "Cambiar el kit de distribución", "Motor",
          "Descripción de las fases de una sustitución de distribución; trabajo reservado a personal cualificado.", "Profesional", "4–8 h", "350–1.200 €",
          ["Útiles de calado específicos", "Llave dinamométrica", "Herramientas de soporte"], ["Kit de distribución", "Bomba de agua si corresponde", "Tornillería indicada"],
          ["Un calado incorrecto puede destruir el motor.", "No realices este trabajo sin datos técnicos y útiles específicos.", COMMON_SPEC_WARNING],
          ["Identifica motor, intervalo y procedimiento oficial.", "Sostén el motor y desmonta accesos según manual.", "Cala cigüeñal y árboles con útiles específicos.", "Sustituye componentes y tensa según procedimiento.", "Gira a mano, verifica calado, monta y comprueba sin anomalías."]),
    guide(24, "diagnosticar-embrague", "Diagnosticar problemas de embrague", "Transmisión",
          "Diferenciación inicial de patinamiento, vibración, ruido o dificultad de accionamiento.", "Media", "20–60 min", "0–80 €",
          ["Linterna", "Herramientas de diagnosis si aplica"], [],
          ["No fuerces pruebas que puedan inmovilizar el vehículo.", "La sustitución del embrague requiere equipamiento profesional."],
          ["Anota cuándo aparece el síntoma.", "Comprueba recorrido o sistema hidráulico.", "Busca fugas y ruidos.", "Evalúa patinamiento sin abuso.", "Relaciona síntomas con embrague, volante, collarín o mando y solicita confirmación."]),
    guide(25, "cambiar-amortiguadores", "Cambiar amortiguadores", "Suspensión",
          "Sustitución orientativa de amortiguadores o conjuntos de suspensión.", "Difícil", "2–5 h", "180–700 €",
          ["Gato y borriquetas", "Llave dinamométrica", "Compresor de muelles homologado si aplica"], ["Amortiguadores", "Copelas y guardapolvos si procede"],
          [COMMON_LIFT_WARNING, "Un muelle comprimido almacena mucha energía; usa equipo homologado o un taller.", "Realiza alineación cuando el diseño lo requiera."],
          ["Confirma el diagnóstico y el tipo de conjunto.", "Eleva y apoya el vehículo.", "Libera fijaciones y soporta el conjunto.", "Sustituye componentes siguiendo el orden exacto.", "Aprieta en posición indicada, alinea y prueba."]),
    guide(26, "revisar-rotulas-direccion", "Revisar rótulas de dirección", "Dirección",
          "Comprobación inicial de holguras, guardapolvos y síntomas de dirección.", "Media", "30–60 min", "0–60 €",
          ["Gato y borriquetas", "Palanca de inspección", "Linterna"], [],
          [COMMON_LIFT_WARNING, "Una holgura de dirección puede comprometer el control del vehículo."],
          ["Confirma vibración, ruido o desgaste irregular.", "Eleva y apoya el eje.", "Inspecciona guardapolvos y corrosión.", "Comprueba holgura sin confundirla con otros componentes.", "Si hay juego, inmoviliza o repara y realiza alineación."]),
    guide(27, "diagnosticar-desalineacion", "Diagnosticar una posible desalineación", "Dirección",
          "Comprobaciones previas cuando el coche se desvía o desgasta neumáticos de forma irregular.", "Fácil", "15–30 min", "0–50 €",
          ["Manómetro", "Medidor de profundidad opcional"], [],
          ["Una desviación también puede deberse a neumáticos, frenos o suspensión."],
          ["Iguala presiones en frío.", "Inspecciona daños y desgaste.", "Comprueba si el volante queda descentrado.", "Observa la desviación solo en un lugar seguro.", "Solicita revisión de suspensión y alineación con equipo calibrado."]),
    guide(28, "diagnosticar-egr", "Diagnosticar la válvula EGR", "Motor",
          "Ruta inicial ante pérdida de potencia, humo o códigos relacionados con recirculación.", "Media", "30–120 min", "0–120 €",
          ["Escáner OBD", "Herramientas básicas"], [],
          ["No sustituyas la EGR basándote solo en un código.", "No anules sistemas anticontaminación."],
          ["Lee códigos y datos congelados.", "Revisa admisión, vacío, conexiones y conductos.", "Compara posición ordenada y real si está disponible.", "Descarta sensores y obstrucciones relacionadas.", "Limpia o sustituye solo tras confirmar la causa."]),
    guide(29, "revisar-caudalimetro-maf", "Revisar el caudalímetro MAF", "Motor",
          "Comprobación de admisión y señal del sensor de masa de aire.", "Media", "20–60 min", "0–100 €",
          ["Escáner OBD", "Multímetro según procedimiento", "Limpiador específico si procede"], [],
          ["No toques el elemento sensible.", "Usa únicamente limpiador específico y solo cuando el fabricante lo permita."],
          ["Lee códigos y datos en vivo.", "Inspecciona filtro, manguitos y fugas.", "Revisa conector y cableado.", "Compara la lectura con condiciones de funcionamiento.", "Limpia o sustituye solo con diagnóstico confirmado."]),
    guide(30, "diagnosticar-sonda-lambda", "Diagnosticar una sonda lambda", "Motor",
          "Comprobación inicial de sensores de oxígeno y condiciones que alteran su lectura.", "Difícil", "45–120 min", "20–150 €",
          ["Escáner OBD", "Multímetro u osciloscopio según procedimiento"], [],
          ["El escape alcanza temperaturas muy elevadas.", "Una mezcla incorrecta o fuga puede simular un sensor defectuoso."],
          ["Lee códigos y datos congelados.", "Busca fugas de admisión y escape.", "Comprueba calentador, cableado y alimentación.", "Analiza respuesta del sensor con el método correcto.", "Corrige la causa y verifica los monitores después."]),
    guide(31, "cambiar-bobina-encendido", "Cambiar una bobina de encendido", "Motor",
          "Sustitución de una bobina después de confirmar un fallo de encendido.", "Fácil", "20–60 min", "25–120 €",
          ["Escáner OBD", "Herramientas básicas"], ["Bobina compatible"],
          ["Trabaja con el contacto apagado.", "Confirma que bujía, inyector y compresión no sean la causa."],
          ["Identifica el cilindro afectado.", "Confirma el fallo con una prueba apropiada.", "Desconecta conector y fijación.", "Monta la bobina nueva sin forzar el aislante.", "Borra códigos si procede y comprueba el funcionamiento."]),
    guide(32, "diagnosticar-inyectores", "Diagnosticar inyectores", "Motor",
          "Comprobaciones iniciales ante fallo de cilindro, consumo o arranque irregular.", "Profesional", "60–180 min", "40–250 €",
          ["Escáner OBD", "Equipo de medición adecuado"], [],
          ["Los sistemas de inyección directa trabajan a alta presión.", "No abras conductos presurizados sin procedimiento y protección."],
          ["Lee códigos y correcciones.", "Descarta encendido, compresión y fugas.", "Comprueba señal eléctrica con método seguro.", "Realiza prueba de equilibrio o retorno cuando corresponda.", "Repara, codifica y verifica solo tras identificar el inyector defectuoso."]),
    guide(33, "diagnosticar-aire-acondicionado", "Diagnosticar el aire acondicionado", "Climatización",
          "Ruta inicial cuando el sistema enfría poco o no conecta.", "Media", "30–90 min", "0–100 €",
          ["Termómetro", "Escáner OBD opcional"], [],
          ["El refrigerante debe recuperarse con equipo autorizado.", "No liberes gas ni uses recargas sin comprobar fugas y tipo de refrigerante."],
          ["Comprueba mandos, ventilador y temperatura de salida.", "Revisa fusibles y señales visibles.", "Observa si el compresor es comandado.", "Busca indicios de fuga y comprueba presiones en taller.", "Repara la fuga antes de cargar la cantidad especificada."]),
    guide(34, "cambiar-bomba-lavaparabrisas", "Cambiar la bomba lavaparabrisas", "Electricidad",
          "Diagnóstico y sustitución de la bomba cuando no llega líquido a los difusores.", "Fácil", "30–90 min", "15–80 €",
          ["Multímetro", "Herramientas básicas", "Recipiente"], ["Bomba compatible", "Junta si aplica"],
          ["Descarta primero depósito vacío, hielo, tubería suelta o difusores obstruidos."],
          ["Acciona el sistema y escucha la bomba.", "Revisa fusible, tuberías y difusores.", "Comprueba alimentación en el conector.", "Accede, desconecta y sustituye la bomba.", "Rellena, purga y verifica fugas y chorro."]),
    guide(35, "cambiar-elevalunas", "Cambiar el mecanismo elevalunas", "Carrocería",
          "Sustitución orientativa del mecanismo cuando el cristal no sube correctamente.", "Difícil", "90–240 min", "60–300 €",
          ["Palancas de guarnecido", "Juego de puntas", "Cinta de sujeción"], ["Mecanismo o motor según diagnóstico", "Grapas"],
          ["Sujeta el cristal antes de liberar el mecanismo.", "Desconecta la batería si el manual lo exige por airbags laterales."],
          ["Confirma alimentación, interruptor y mecanismo.", "Retira el panel sin romper grapas.", "Sujeta el cristal.", "Sustituye mecanismo o motor respetando rutas de cables.", "Calibra límites si aplica y monta el panel."]),
    guide(36, "cambiar-espejo-retrovisor", "Cambiar un espejo retrovisor", "Carrocería",
          "Sustitución del cristal o conjunto exterior después de identificar sus funciones.", "Media", "30–120 min", "25–350 €",
          ["Palancas de guarnecido", "Juego de puntas"], ["Cristal o retrovisor compatible", "Grapas si aplica"],
          ["Confirma calefacción, plegado, cámara y detector de ángulo muerto antes de comprar."],
          ["Identifica si se cambia cristal o conjunto.", "Protege pintura y guarnecidos.", "Desmonta acceso y conectores.", "Monta la pieza compatible.", "Comprueba regulación, calefacción y sistemas de asistencia."]),
    guide(37, "limpiar-climatizacion", "Limpiar y desinfectar la climatización", "Climatización",
          "Limpieza básica del sistema de ventilación y sustitución del filtro.", "Fácil", "30–60 min", "15–60 €",
          ["Guantes", "Producto autorizado para automoción"], ["Filtro de habitáculo"],
          ["Sigue exactamente las instrucciones del producto.", "No pulverices líquidos sobre componentes eléctricos."],
          ["Retira residuos de las tomas de aire.", "Sustituye el filtro del habitáculo.", "Aplica el método de limpieza autorizado.", "Ventila el vehículo completamente.", "Comprueba olor, caudal y drenaje del evaporador."]),
    guide(38, "diagnosticar-filtro-particulas-dpf", "Diagnosticar el filtro de partículas DPF", "Emisiones",
          "Interpretación inicial de avisos de saturación y problemas de regeneración.", "Profesional", "45–180 min", "30–250 €",
          ["Escáner de diagnosis", "Equipo de medición adecuado"], [],
          ["No fuerces una regeneración sin comprobar nivel de saturación, aceite y causas.", "La regeneración eleva mucho la temperatura del escape."],
          ["Lee códigos, carga calculada y presión diferencial.", "Revisa sensores, tubos y temperatura.", "Busca causas de hollín excesivo.", "Decide si procede regeneración, limpieza o sustitución.", "Verifica contrapresión y corrige la causa original."]),
    guide(39, "diagnosticar-turbo", "Diagnosticar problemas de turbo", "Motor",
          "Ruta inicial ante pérdida de potencia, silbido, humo o presión incorrecta.", "Profesional", "60–180 min", "30–300 €",
          ["Escáner OBD", "Herramientas de inspección"], [],
          ["No aceleres un motor con ruidos, humo intenso o consumo de aceite.", "Una fuga o actuador puede imitar un turbo averiado."],
          ["Lee códigos y presión solicitada/real.", "Inspecciona manguitos, intercooler y abrazaderas.", "Comprueba control de vacío o actuador.", "Revisa lubricación y holguras con criterio profesional.", "Corrige la causa y limpia el circuito cuando el procedimiento lo exija."]),
    guide(40, "diagnosticar-fuga-refrigerante", "Diagnosticar una fuga de refrigerante", "Refrigeración",
          "Localización inicial de pérdidas externas o internas del circuito.", "Media", "30–120 min", "0–150 €",
          ["Linterna", "Equipo de presión en taller", "Guantes"], [],
          ["Nunca abras el depósito en caliente.", "No circules si el motor se sobrecalienta o pierde rápidamente el nivel."],
          ["Deja enfriar y comprueba nivel.", "Inspecciona manguitos, radiador, bomba y uniones.", "Busca residuos secos, humedad y olor.", "Realiza prueba de presión y gases si procede.", "Repara la causa, rellena, purga y verifica en frío."]),
]

GUIDES_BY_SLUG = {item["slug"]: item for item in GUIDES}

OBD_GUIDES = {
    "P0420": {"title": "Eficiencia del catalizador por debajo del umbral (Banco 1)", "description": "La unidad detecta una eficacia del catalizador inferior a la esperada.", "causes": ["Catalizador degradado", "Fuga de escape", "Sonda lambda o cableado", "Mezcla o fallos de combustión previos"], "checks": ["Leer códigos asociados y datos congelados", "Revisar fugas", "Analizar señales de las sondas", "Corregir fallos de mezcla o encendido antes de condenar el catalizador"]},
    "P0301": {"title": "Fallo de encendido detectado en cilindro 1", "description": "Se ha detectado combustión irregular en el cilindro 1.", "causes": ["Bujía o bobina", "Inyector", "Fuga de admisión", "Compresión insuficiente"], "checks": ["Revisar datos congelados", "Comprobar encendido", "Comprobar inyector", "Medir compresión si persiste"]},
    "P0171": {"title": "Mezcla demasiado pobre (Banco 1)", "description": "La corrección de combustible necesaria supera el rango esperado.", "causes": ["Entrada de aire no medida", "Caudalímetro", "Presión de combustible baja", "Fuga de escape"], "checks": ["Analizar fuel trims", "Buscar fugas de vacío", "Revisar MAF", "Comprobar presión de combustible"]},
    "P0101": {"title": "Rango o rendimiento del caudalímetro", "description": "La lectura del MAF no concuerda con otras variables del motor.", "causes": ["MAF contaminado o defectuoso", "Fuga de admisión", "Filtro obstruido", "Cableado"], "checks": ["Inspeccionar admisión", "Revisar conector", "Comparar datos en vivo", "Descartar fugas"]},
    "P0401": {"title": "Flujo insuficiente de recirculación EGR", "description": "El flujo EGR observado es inferior al previsto.", "causes": ["Conductos obstruidos", "EGR atascada", "Actuador", "Sensor relacionado"], "checks": ["Leer datos en vivo", "Comprobar mando y posición", "Inspeccionar conductos", "Confirmar sensores antes de sustituir"]},
}
